### PR TITLE
feat: added login and signup pages

### PR DESCRIPTION
**Pull request by amarphule**
Created Authentication pages
1. Login page
2. SignUp page

### CODE REVIEW

**Review by AmishMishra11 — COMMENTED** [review]
Code is good just add media query and decrease the font size.

**Comment by amarphule** [comment]
> Code is good just add media query and decrease the font size.

yes Once I finish with all pages, I'll do that. Thank you for pointing it out.

**Comment by Roshannair24** [comment]
looks good to merge. just correct they typo in the placeholder..' what are you looking *for'

**Review by Roshannair24 — APPROVED** [review]

**Comment by amarphule** [comment]
> looks good to merge. just correct the typo in the placeholder..' what are you looking *for'

Sorry but I'm not getting it. what are you trying to say?

**Pull request merged**
